wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: huggingface
    huggingface_version: 4.18.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.9
    start_time: 1651844809
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 2
      4: 3.8.9
      5: 0.12.16
      6: 4.18.0
      8:
      - 1
      - 5
